town_to_team = {'Arizona': 'Arizona Cardinals',
                'Atlanta': 'Atlanta Falcons',
                'Baltimore': 'Baltimore Ravens',
                'Buffalo': 'Buffalo Bills',
                'Carolina': 'Carolina Panthers',
                'Chicago': 'Chicago Bears',
                'Cincinnati': 'Cincinnati Bengals',
                'Cleveland': 'Cleveland Browns',
                'Dallas': 'Dallas Cowboys',
                'Denver': 'Denver Broncos',
                'Detroit': 'Detroit Lions',
                'Green Bay': 'Green Bay Packers',
                'Houston': 'Houston Texans',
                'Indianapolis': 'Indianapolis Colts',
                'Jacksonville': 'Jacksonville Jaguars',
                'Kansas City': 'Kansas City Chiefs',
                'LA Chargers': 'Los Angeles Chargers',
                'LA Rams': 'Los Angeles Rams',
                'Miami': 'Miami Dolphins',
                'Minnesota': 'Minnesota Vikings',
                'New England': 'New England Patriots',
                'New Orleans': 'New Orleans Saints',
                'NY Giants': 'New York Giants',
                'NY Jets': 'New York Jets',
                'Oakland': 'Oakland Raiders',
                'Philadelphia': 'Philadelphia Eagles',
                'Pittsburgh': 'Pittsburgh Steelers',
                'San Francisco': 'San Francisco 49ers',
                'Seattle': 'Seattle Seahawks',
                'Tampa Bay': 'Tampa Bay Buccaneers',
                'Tennessee': 'Tennessee Titans',
                'Washington': 'Washington Redskins'}