town_to_team = {'Arizona': 'Arizona Cardinals',
                'Atlanta': 'Atlanta Falcons',
                'Baltimore': 'Baltimore Ravens',
                'Buffalo': 'Buffalo Bills',
                'Carolina': 'Carolina Panthers',
                'Chicago': 'Chicago Bears',
                'Cincinnati': 'Cincinnati Bengals',
                'Cleveland': 'Cleveland Browns',
                'Dallas': 'Dallas Cowboys',
                'Denver': 'Denver Broncos',
                'Detroit': 'Detroit Lions',
                'Green Bay': 'Green Bay Packers',
                'Houston': 'Houston Texans',
                'Indianapolis': 'Indianapolis Colts',
                'Jacksonville': 'Jacksonville Jaguars',
                'Kansas City': 'Kansas City Chiefs',
                'LA Chargers': 'Los Angeles Chargers',
                'LA Rams': 'Los Angeles Rams',
                'Miami': 'Miami Dolphins',
                'Minnesota': 'Minnesota Vikings',
                'New England': 'New England Patriots',
                'New Orleans': 'New Orleans Saints',
                'NY Giants': 'New York Giants',
                'NY Jets': 'New York Jets',
                'Oakland': 'Oakland Raiders',
                'Philadelphia': 'Philadelphia Eagles',
                'Pittsburgh': 'Pittsburgh Steelers',
                'San Francisco': 'San Francisco 49ers',
                'Seattle': 'Seattle Seahawks',
                'Tampa Bay': 'Tampa Bay Buccaneers',
                'Tennessee': 'Tennessee Titans',
                'Washington': 'Washington Redskins'}

tr_stat_list = {'sacks_defense_list': {'url': 'https://www.teamrankings.com/nfl/stat/sacks-per-game',
                                       'column_name': 'sacks_created'},
                'sacks_offense_list': {'url': 'https://www.teamrankings.com/nfl/stat/qb-sacked-per-game',
                                       'column_name': 'sacks_thrown'},
                'interceptions_thrown': {'url': 'https://www.teamrankings.com/nfl/stat/interceptions-thrown-per-game',
                                         'column_name': 'interceptions_thrown'},
                'interceptions_created': {'url': 'https://www.teamrankings.com/nfl/stat/interceptions-per-game',
                                          'column_name': 'interceptions_created'},
                'fumbles_thrown': {'url': 'https://www.teamrankings.com/nfl/stat/fumbles-per-game',
                                   'column_name': 'fumbles_thrown'},
                'fumbles_created': {'url': 'https://www.teamrankings.com/nfl/stat/opponent-fumbles-per-game',
                                    'column_name': 'fumbles_created'},
                'defensive_touchdowns': {'url': 'https://www.teamrankings.com/nfl/stat/defensive-touchdowns-per-game',
                                         'column_name': 'defensive_touchdowns'}}