town_to_team = {
    "Arizona": "Arizona Cardinals",
    "Atlanta": "Atlanta Falcons",
    "Baltimore": "Baltimore Ravens",
    "Buffalo": "Buffalo Bills",
    "Carolina": "Carolina Panthers",
    "Chicago": "Chicago Bears",
    "Cincinnati": "Cincinnati Bengals",
    "Cleveland": "Cleveland Browns",
    "Dallas": "Dallas Cowboys",
    "Denver": "Denver Broncos",
    "Detroit": "Detroit Lions",
    "Green Bay": "Green Bay Packers",
    "Houston": "Houston Texans",
    "Indianapolis": "Indianapolis Colts",
    "Jacksonville": "Jacksonville Jaguars",
    "Kansas City": "Kansas City Chiefs",
    "LA Chargers": "Los Angeles Chargers",
    "LA Rams": "Los Angeles Rams",
    "Miami": "Miami Dolphins",
    "Minnesota": "Minnesota Vikings",
    "New England": "New England Patriots",
    "New Orleans": "New Orleans Saints",
    "NY Giants": "New York Giants",
    "NY Jets": "New York Jets",
    "Oakland": "Oakland Raiders",
    "Philadelphia": "Philadelphia Eagles",
    "Pittsburgh": "Pittsburgh Steelers",
    "San Francisco": "San Francisco 49ers",
    "Seattle": "Seattle Seahawks",
    "Tampa Bay": "Tampa Bay Buccaneers",
    "Tennessee": "Tennessee Titans",
    "Washington": "Washington Redskins",
}

tr_stat_list = {
    "sacks_defense_list": {
        "url": "https://www.teamrankings.com/nfl/stat/sacks-per-game",
        "column_name": "sacks_created",
    },
    "sacks_offense_list": {
        "url": "https://www.teamrankings.com/nfl/stat/qb-sacked-per-game",
        "column_name": "sacks_thrown",
    },
    "interceptions_thrown": {
        "url": "https://www.teamrankings.com/nfl/stat/interceptions-thrown-per-game",
        "column_name": "interceptions_thrown",
    },
    "interceptions_created": {
        "url": "https://www.teamrankings.com/nfl/stat/interceptions-per-game",
        "column_name": "interceptions_created",
    },
    "fumbles_thrown": {
        "url": "https://www.teamrankings.com/nfl/stat/fumbles-per-game",
        "column_name": "fumbles_thrown",
    },
    "fumbles_created": {
        "url": "https://www.teamrankings.com/nfl/stat/opponent-fumbles-per-game",
        "column_name": "fumbles_created",
    },
    "defensive_touchdowns": {
        "url": "https://www.teamrankings.com/nfl/stat/defensive-touchdowns-per-game",
        "column_name": "defensive_touchdowns",
    },
}

defense_pure_list = ["interceptions_created", "fumbles_created", "defensive_touchdowns"]

poisson_events = {
    "points_allowed": 50,
    "sacks_created": 7,
    "interceptions_created": 7,
    "fumbles_created": 5,
    "defensive_touchdowns": 4,
    "sacks_thrown": 7,
    "interceptions_thrown": 7,
    "fumbles_thrown": 5,
}

defense_opponent_list = ["fumbles", "interceptions", "sacks"]

qb_to_team = {
    "Kyler Murray": "Arizona Cardinals",
    "Matt Ryan": "Atlanta Falcons",
    "Lamar Jackson": "Baltimore Ravens",
    "Josh Allen": "Buffalo Bills",
    "Cam Newton": "Carolina Panthers",
    "Mitch Trubisky": "Chicago Bears",
    "Andy Dalton": "Cincinnati Bengals",
    "Baker Mayfield": "Cleveland Browns",
    "Dak Prescott": "Dallas Cowboys",
    "Joe Flacco": "Denver Broncos",
    "Matthew Stafford": "Detroit Lions",
    "Aaron Rodgers": "Green Bay Packers",
    "Deshaun Watson": "Houston Texans",
    "Jacoby Brisett": "Indianapolis Colts",
    "Nick Foles": "Jacksonville Jaguars",
    "Patrick Mahomes": "Kansas City Chiefs",
    "Phillip Rivers": "Los Angeles Chargers",
    "Jared Goff": "Los Angeles Rams",
    "Ryan Fitzpatrick": "Miami Dolphins",
    "Kirk Cousins": "Minnesota Vikings",
    "Tom Brady": "New England Patriots",
    "Drew Brees": "New Orleans Saints",
    "Eli Manning": "New York Giants",
    "Sam Darnold": "New York Jets",
    "Derek Carr": "Oakland Raiders",
    "Carson Wentz": "Philadelphia Eagles",
    "Ben Roethlisberger": "Pittsburgh Steelers",
    "Jimmy Garoppolo": "San Francisco 49ers",
    "Russell Wilson": "Seattle Seahawks",
    "Jameis Winston": "Tampa Bay Buccaneers",
    "Marcus Mariota": "Tennessee Titans",
    "Case Keenum": "Washington Redskins",
}
